10 PRINT "HELLO WORLD": REM THIS A COMMENT
20 PRINT "THIS IS A BASIC PROGRAM": REM THIS IS ANOTHER COMMENT
30 PRINT "ONE MESSAGE IN A LINE": PRINT "ANOTHER MESSAGE IN THE SAME LINE"
30 PRINT "THIS IS THE END": END
